# Reproduce the familiarity/novelty manuscript figures and supplementary tables

This is the single reviewer-facing entry point. It validates the supplied Main Figure 1 design asset and regenerates Main Figures 2–5, Supplementary Figures 1–11, Supplementary Tables 1–16, and both unnumbered supplementary tabular displays.

Only anonymized preprocessed participant data and compact final analysis/display tables are used. Raw task files and task code are not required.

## Reproduction boundary

- Supplementary Figure 2 recomputes the N-F-1 participant-balanced trajectories and pointwise 95% t intervals from `data/n-f-1-participant-trajectories.csv`, then checks them against the frozen display summary.
- Supplementary Tables 4–7 recompute 66 correlation/BH-FDR rows from `data/n-f-2-to-5-participants.csv`; those values are cross-checked against the frozen Main Figure 3/4 display inputs before plotting.
- Table 8 refits its point estimates and validates the frozen 10,000-resample intervals.
- Trajectory/HLM, bootstrap, reliability, and sensitivity panels use compact plot-ready or result-level CSVs; upstream task preprocessing is intentionally outside this release.
- The plotting modules fix the active manuscript artboards, Arial typography, colors, markers, line styles, panel labels, and annotations.

In [1]:
from pathlib import Path
import sys

import pandas as pd

ROOT = Path.cwd().resolve()
if ROOT.name == 'notebooks':
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT / 'code'))

import reproduce_all
import validate

pd.set_option('display.max_columns', 40)
print('Repository root resolved; paths in released outputs remain relative.')

Repository root resolved; paths in released outputs remain relative.

## 1. Inspect and validate the anonymized participant cohorts

The released inputs retain the manuscript denominators: 15 N-F-1 pilot participants, 305 E2–E5 completers, 303 primary participants, and 153 primary E3/E5 matched participants.

In [2]:
experiment1 = pd.read_csv(ROOT / 'data' / 'n-f-1-participant-trajectories.csv')
participants = pd.read_csv(ROOT / 'data' / 'n-f-2-to-5-participants.csv')
participants['in_primary'] = participants['in_primary'].astype(str).str.lower().map({'true': True, 'false': False})
cohorts = (
    participants.groupby(['experiment', 'in_primary'], dropna=False)
    .size().rename('n').reset_index()
)
assert len(participants) == 305
assert int(participants['in_primary'].sum()) == 303
assert len(participants.query('experiment in [3, 5] and in_primary')) == 153
assert len(experiment1) == 1560
assert experiment1['experiment1_record_id'].nunique() == 15
assert set(experiment1['category']) == {'Face', 'Scenery', 'Geometry', 'Car'}
assert set(experiment1['comparison_position']) == set(range(1, 27))
display(experiment1.groupby('category', sort=False).agg(rows=('familiar_target_preference', 'size'), participants=('experiment1_record_id', 'nunique')))
display(cohorts)

          rows  participants
category
Face       390            15
Scenery    390            15
Geometry   390            15
Car        390            15

   experiment  in_primary    n
0           2        True   24
1           3        True   22
2           4        True  126
3           5       False    2
4           5        True  131

## 2. Trace every output to its compact inputs

The release manifest gives a direct, reviewer-readable route from each of the 34 figure/table components to its input CSV files or editable source and states whether the step recomputes an analysis, rerenders frozen results, or retains a canonical design asset.

In [3]:
output_inputs = pd.read_csv(ROOT / 'data' / 'output_input_manifest.csv')
data_dictionary = pd.read_csv(ROOT / 'data' / 'participant_data_dictionary.csv')
assert len(output_inputs) == 34
assert set(participants.columns) == set(data_dictionary['release_column'])
display(output_inputs)
display(data_dictionary)

,output_file,input_files,reproduction_level,note
0,outputs/figures/main/main_figure_01.pdf,source/figure_01/main_figure_01_editable.pptx,editable design source + canonical PDF,Conceptual main-manuscript figure; no statisti...
1,outputs/figures/main/main_figure_02.pdf,data/main/figure02/observed_trajectory.csv; da...,plot-data rendering,Active main-manuscript design and artboard
2,outputs/figures/main/main_figure_03.pdf,data/n-f-2-to-5-participants.csv; data/main/fi...,recomputed correlation family + frozen display...,Active main-manuscript design and artboard
3,outputs/figures/main/main_figure_04.pdf,data/n-f-2-to-5-participants.csv; data/main/fi...,recomputed correlation family + frozen display...,Active main-manuscript design and artboard
4,outputs/figures/main/main_figure_05.pdf,data/main/figure05/moderator_screen_bh12.csv; ...,frozen model/result rendering,Active main-manuscript design and artboard
5,outputs/figures/supplement/supplementary_figur...,data/supplement/figure_01_demographics/age_poi...,aggregate/plot-data rendering,Active Supplementary Information design and ar...
6,outputs/figures/supplement/supplementary_figur...,data/n-f-1-participant-trajectories.csv; data/...,recomputed participant-balanced trajectory + f...,Active Supplementary Information design and ar...
7,outputs/figures/supplement/supplementary_figur...,data/supplement/figure_03_experiment4_trajecto...,aggregate/plot-data rendering,Active Supplementary Information design and ar...
8,outputs/figures/supplement/supplementary_figur...,data/supplement/figure_04_fni_patterns/margina...,aggregate/plot-data rendering,Active Supplementary Information design and ar...
9,outputs/figures/supplement/supplementary_figur...,data/supplement/figure_05_selected_profiles/se...,aggregate/plot-data rendering,Active Supplementary Information design and ar...
10,outputs/figures/supplement/supplementary_figur...,data/supplement/figure_06_equivalence/plot_dat...,frozen analysis-result rendering,Active Supplementary Information design and ar...
11,outputs/figures/supplement/supplementary_figur...,data/supplement/figure_07_joint_model/model_fi...,frozen analysis-result rendering,Active Supplementary Information design and ar...
12,outputs/figures/supplement/supplementary_figur...,data/supplement/figure_08_negative_capability/...,frozen analysis-result rendering,Active Supplementary Information design and ar...
13,outputs/figures/supplement/supplementary_figur...,data/supplement/figure_09_aq_benefits/plot_dat...,frozen analysis-result rendering,Active Supplementary Information design and ar...
14,outputs/figures/supplement/supplementary_figur...,data/supplement/figure_10_hlm_moderators/guide...,frozen analysis-result rendering,Active Supplementary Information design and ar...
15,outputs/figures/supplement/supplementary_figur...,data/supplement/figure_11_reliability/panel_a....,frozen analysis-result rendering,Active Supplementary Information design and ar...
16,outputs/tables/supplementary_table_01.tex,data/tables/table01_analysis_populations.csv,frozen aggregate/result + TeX rendering,Active supplementary table component
17,outputs/tables/supplementary_table_02.tex,data/tables/table02_visual_task_implementation...,frozen aggregate/result + TeX rendering,Active supplementary table component
18,outputs/tables/supplementary_table_03.tex,data/tables/table03_age_gender.csv; data/table...,frozen aggregate/result + TeX rendering,Active supplementary table component
19,outputs/tables/supplementary_table_04.tex,data/n-f-2-to-5-participants.csv,recomputed analysis + TeX rendering,Active supplementary table component
20,outputs/tables/supplementary_table_05.tex,data/n-f-2-to-5-participants.csv; data/tables/...,recomputed analysis + TeX rendering,Active supplementary table component
21,outputs/tables/supplementary_table_06.tex,data/n-f-2-to-5-participants.csv,recomputed analysis + TeX rendering,Active supplementary table component
22,outputs/tables/supplementary_table_07.tex,data/n-f-2-to-5-participants.csv,recomputed analysis + TeX rendering,Active supplementary table component
23,outputs/tables/supplementary_table_08.tex,data/n-f-2-to-5-participants.csv; data/tables/...,recomputed analysis + TeX rendering,Active supplementary table component
24,outputs/tables/supplementary_table_09.tex,data/tables/table09_primary_trajectories.csv,frozen aggregate/result + TeX rendering,Active supplementary table component
25,outputs/tables/supplementary_table_10.tex,data/tables/table10_trajectory_sensitivities.csv,frozen aggregate/result + TeX rendering,Active supplementary table component
26,outputs/tables/supplementary_table_11.tex,data/tables/table11_trait_moderation.csv,frozen aggregate/result + TeX rendering,Active supplementary table component
27,outputs/tables/supplementary_table_12.tex,data/tables/table12_joint_trait_moderation.csv,frozen aggregate/result + TeX rendering,Active supplementary table component
28,outputs/tables/supplementary_table_13.tex,data/tables/table13_daily_item_moderation.csv,frozen aggregate/result + TeX rendering,Active supplementary table component
29,outputs/tables/supplementary_table_14.tex,data/tables/table14_cross_subcategory_stabilit...,frozen aggregate/result + TeX rendering,Active supplementary table component
30,outputs/tables/supplementary_table_15.tex,data/tables/table15_stimulus_taxonomy.csv,frozen aggregate/result + TeX rendering,Active supplementary table component
31,outputs/tables/supplementary_table_16.tex,data/tables/table16_questionnaire_features.csv,frozen aggregate/result + TeX rendering,Active supplementary table component
32,outputs/tables/supplementary_inline_01.tex,data/tables/inline01_cross_reference.csv,frozen metadata + TeX rendering,Unnumbered supplementary cross-reference display
33,outputs/tables/supplementary_inline_02.tex,data/tables/inline02_face_fni_adjusted_joint.csv,frozen result + TeX rendering,Unnumbered Face-FNI robustness display

,release_column,original_or_manuscript_name,data_type,scale_or_theoretical_range,observed_range_or_levels,nonmissing_n,description
0,analysis_record_id,release pseudonym,string,A001--A305,305 unique release values,305,Join key for released analysis tables; not a p...
1,experiment,experiment,integer,2--5,2 to 5,305,Experiment number.
2,mode,setting,category,lab or online,lab; online,305,Data-collection mode.
3,in_primary,QC-clean membership,boolean,True or False,False; True,305,True for the frozen primary integrated cohort ...
4,face_fni,Face FNI,number,theoretical -3 to +3,-1.86 to 2.63853,305,Participant Face familiarity/novelty index; hi...
5,geometry_fni,Geometry FNI,number,theoretical -3 to +3,-1.9025 to 2.42059,305,Participant Geometry familiarity/novelty index...
6,scenery_fni,Scenery FNI,number,theoretical -3 to +3,-2.27941 to 1.94118,305,Participant Scenery familiarity/novelty index;...
7,aq_score,AQ_score,integer,0--50,5 to 43,305,Autism-Spectrum Quotient total; higher values ...
8,daily_familiarity,4_NF-daily / 4_nf_daily,number,-3 to +3,-3 to 3,305,Mean of eight daily novelty/familiarity items;...
9,maemuki_score,Maemuki_score,number,approximately -3 to +3,-1.0844 to 2.416,305,Composite positive/forward psychological orien...
10,flow_original,10_Flow-attitude,number,-3 to +3,-1.15385 to 2.92308,305,Historical experiment-specific Flow implementa...
11,flow_common12,10_Flow-attitude common 12,number,-3 to +3,-1.08333 to 2.91667,305,Harmonized common-12 Flow score used in the ob...
12,negative_capability,12_Negative_Capability,number,-3 to +3,-3 to 3,281,Nine-item Negative Capability score; collected...
13,novelty_benefit,4_1_N-affect_daily,number,-3 to +3,-3 to 3,305,Mean perceived positive benefit of novelty see...
14,familiarity_benefit,4_2_F-affect_daily,number,-3 to +3,-3 to 3,305,Mean perceived positive benefit of familiarity...
15,daily_food,4_food/cuisine,integer,-3 to +3,-3 to 3,305,Daily food novelty/familiarity item; higher va...
16,daily_places,4_places/activities,integer,-3 to +3,-3 to 3,305,Daily places/activities novelty/familiarity it...
17,daily_movies,4_movies or videos,integer,-3 to +3,-3 to 3,305,Daily movies/videos novelty/familiarity item; ...
18,daily_restaurant,4_restaurant,integer,-3 to +3,-3 to 3,305,Daily restaurant novelty/familiarity item; hig...
19,daily_clothes,4_clothes,integer,-3 to +3,-3 to 3,305,Daily clothes novelty/familiarity item; higher...
20,daily_games,4_digital games,integer,-3 to +3,-3 to 3,305,Daily digital-games novelty/familiarity item; ...
21,daily_books,4_books or magazines,integer,-3 to +3,-3 to 3,305,Daily books/magazines novelty/familiarity item...
22,daily_snacks,4_snacks or treats,integer,-3 to +3,-3 to 3,305,Daily snacks/treats novelty/familiarity item; ...

## 3. Regenerate every figure and table

The command below uses the same functions as `python code/reproduce_all.py`. Existing outputs are overwritten.

In [4]:
import json
import subprocess

completed = subprocess.run(
    [sys.executable, str(ROOT / 'code' / 'reproduce_all.py')],
    cwd=ROOT,
    check=True,
    capture_output=True,
    text=True,
)
print(completed.stdout)
run = json.loads((ROOT / 'outputs' / 'run_manifest.json').read_text())

{
  "main_figures": [
    "outputs/figures/main/main_figure_01.pdf",
    "outputs/figures/main/main_figure_02.pdf",
    "outputs/figures/main/main_figure_03.pdf",
    "outputs/figures/main/main_figure_04.pdf",
    "outputs/figures/main/main_figure_05.pdf"
  ],
  "supplementary_figures": [
    "outputs/figures/supplement/supplementary_figure_01.pdf",
    "outputs/figures/supplement/supplementary_figure_02.pdf",
    "outputs/figures/supplement/supplementary_figure_03.pdf",
    "outputs/figures/supplement/supplementary_figure_04.pdf",
    "outputs/figures/supplement/supplementary_figure_05.pdf",
    "outputs/figures/supplement/supplementary_figure_06.pdf",
    "outputs/figures/supplement/supplementary_figure_07.pdf",
    "outputs/figures/supplement/supplementary_figure_08.pdf",
    "outputs/figures/supplement/supplementary_figure_09.pdf",
    "outputs/figures/supplement/supplementary_figure_10.pdf",
    "outputs/figures/supplement/supplementary_figure_11.pdf"
  ],
  "tables": [
    "outputs/tables/supplementary_table_01.tex",
    "outputs/tables/supplementary_table_02.tex",
    "outputs/tables/supplementary_table_03.tex",
    "outputs/tables/supplementary_table_04.tex",
    "outputs/tables/supplementary_table_05.tex",
    "outputs/tables/supplementary_table_06.tex",
    "outputs/tables/supplementary_table_07.tex",
    "outputs/tables/supplementary_table_08.tex",
    "outputs/tables/supplementary_table_09.tex",
    "outputs/tables/supplementary_table_10.tex",
    "outputs/tables/supplementary_table_11.tex",
    "outputs/tables/supplementary_table_12.tex",
    "outputs/tables/supplementary_table_13.tex",
    "outputs/tables/supplementary_table_14.tex",
    "outputs/tables/supplementary_table_15.tex",
    "outputs/tables/supplementary_table_16.tex",
    "outputs/tables/supplementary_inline_01.tex",
    "outputs/tables/supplementary_inline_02.tex",
    "outputs/tables/all_supplementary_tables.tex",
    "outputs/tables/all_supplementary_tables.pdf"
  ],
  "figure_validation": "outputs/figure_validation.csv",
  "table_validation": "outputs/table_validation.csv",
  "data_privacy_validation": "outputs/data_privacy_validation.csv",
  "analysis_crosscheck": "outputs/analysis_crosscheck.csv",
  "author_side_visual_parity": "outputs/manuscript_visual_parity.csv"
}

## 4. Supplementary results: Tables 1–16 and inline displays

The tables below are the supplementary results underlying the publication-formatted TeX outputs. Tables 4–8 use the generated result CSVs created by the reproduction pipeline; the remaining tables use the released aggregate, metadata, or frozen-result inputs. Together they show all 16 numbered Supplementary Tables and the two unnumbered supplementary tabular displays directly in the notebook.

In [5]:
from IPython.display import Markdown, display

supplementary_results = [
    ('Supplementary Table 1. Analysis populations and manuscript roles', [
        ('', 'data/tables/table01_analysis_populations.csv'),
    ]),
    ('Supplementary Table 2. Experiment-specific visual-task implementations', [
        ('', 'data/tables/table02_visual_task_implementations.csv'),
    ]),
    ('Supplementary Table 3. Participant demographics in the primary E2–E5 analysis set', [
        ('Age and recorded gender at birth', 'data/tables/table03_age_gender.csv'),
        ('Recorded race response', 'data/tables/table03_race.csv'),
    ]),
    ('Supplementary Table 4. Matched visual-category FNI by questionnaire associations', [
        ('', 'outputs/tables/supplementary_table_04_data.csv'),
    ]),
    ('Supplementary Table 5. Matched visual-category FNI by Daily familiarity item associations', [
        ('', 'outputs/tables/supplementary_table_05_data.csv'),
    ]),
    ('Supplementary Table 6. Pooled questionnaire-pair associations', [
        ('', 'outputs/tables/supplementary_table_06_data.csv'),
    ]),
    ('Supplementary Table 7. Pooled Daily familiarity item by questionnaire associations', [
        ('', 'outputs/tables/supplementary_table_07_data.csv'),
    ]),
    ('Supplementary Table 8. Questionnaire relationships in the joint model', [
        ('', 'outputs/tables/supplementary_table_08_data.csv'),
    ]),
    ('Supplementary Table 9. Primary category trajectories and pairwise differences', [
        ('', 'data/tables/table09_primary_trajectories.csv'),
    ]),
    ('Supplementary Table 10. Sensitivity analyses for the category trajectories', [
        ('', 'data/tables/table10_trajectory_sensitivities.csv'),
    ]),
    ('Supplementary Table 11. Overall-moderator trajectory family and item-aware sensitivity', [
        ('', 'data/tables/table11_trait_moderation.csv'),
    ]),
    ('Supplementary Table 12. Joint-trait trajectory-moderation sensitivity', [
        ('', 'data/tables/table12_joint_trait_moderation.csv'),
    ]),
    ('Supplementary Table 13. Daily-item moderation family and item-aware sensitivity', [
        ('', 'data/tables/table13_daily_item_moderation.csv'),
    ]),
    ('Supplementary Table 14. Cross-subcategory stability', [
        ('', 'data/tables/table14_cross_subcategory_stability.csv'),
    ]),
    ('Supplementary Table 15. Task-pool stimulus taxonomy across Experiments 1–5', [
        ('', 'data/tables/table15_stimulus_taxonomy.csv'),
    ]),
    ('Supplementary Table 16. Questionnaire-derived features used in Experiments 2–5', [
        ('', 'data/tables/table16_questionnaire_features.csv'),
    ]),
    ('Supplementary inline result 1. Main-text to Supplementary Information cross-reference', [
        ('', 'data/tables/inline01_cross_reference.csv'),
    ]),
    ('Supplementary inline result 2. Face-FNI adjusted and joint-model robustness', [
        ('', 'data/tables/inline02_face_fni_adjusted_joint.csv'),
    ]),
]

assert len(supplementary_results) == 18
for title, sections in supplementary_results:
    display(Markdown(f'### {title}'))
    for section_label, relative_path in sections:
        result_path = ROOT / relative_path
        assert result_path.is_file(), result_path
        if section_label:
            display(Markdown(f'**{section_label}**'))
        display(pd.read_csv(result_path))

print('Displayed all 16 numbered Supplementary Tables and both supplementary inline results.')

### Supplementary Table 1. Analysis populations and manuscript roles

,experiment,setting,completers,qc_clean,manuscript_role
0,1,Laboratory,15,--,Pilot; excluded from current analyses
1,2,Laboratory,24,24,Integrated questionnaire/sample scope
2,3,Laboratory,22,22,Integrated scope; matched visual analysis
3,4,Online,126,126,Integrated scope; descriptive target-shift ana...
4,5,Online,133,131,Integrated scope; matched visual analysis
5,3 and 5 combined,Mixed,155,153,Matched trial-level cohort
6,2--5 combined,Mixed,305,303,Primary integrated questionnaire/sample scope

### Supplementary Table 2. Experiment-specific visual-task implementations

,study,setting_blocks,rating_sequence,preference_sequence
0,1,"Laboratory; two sessions across Face, Scenery,...",Nominally 27 ratings; the archived Diagonal-SU...,26 previously encountered comparisons per subc...
1,2,"Laboratory; eight blocks across Face, Scenery,...",19 rating records per block in all 24 raw expo...,18 comparisons per block; integrated questionn...
2,3,"Laboratory; 12 blocks across Face, Scenery and...",19 ratings; nominal median target (rank 10 of 19),18 comparisons per block; matched visual analysis
3,4,"Online; 12 blocks across Face, Scenery and Geo...",19 ratings; implementation error selected the ...,18 comparisons per block; descriptive design-d...
4,5,"Online; 12 blocks across Face, Scenery and Geo...",19 ratings; corrected median target (rank 10 o...,18 comparisons per block; matched visual analysis

### Supplementary Table 3. Participant demographics in the primary E2–E5 analysis set

**Age and recorded gender at birth**

,experiment,setting,n,age_mean,age_sd,median,age_min,age_max,female_n,female_pct,male_n,male_pct
0,E2,Laboratory,24,25.08,10.24,21.0,18,62,14,58.3,10,41.7
1,E3,Laboratory,22,21.91,6.41,19.0,18,46,14,63.6,8,36.4
2,E4,Online,126,39.60,12.65,36.5,18,81,52,41.3,74,58.7
3,E5,Online,131,36.37,12.16,35.0,19,78,79,60.3,52,39.7
4,Pooled,Mixed,303,35.77,13.04,34.0,18,81,159,52.5,144,47.5

**Recorded race response**

,response,E2,E3,E4,E5,Pooled
0,Asian,19 (79.2\%),12 (54.5\%),14 (11.1\%),20 (15.3\%),65 (21.5\%)
1,Black / African American,0 (0.0\%),0 (0.0\%),13 (10.3\%),21 (16.0\%),34 (11.2\%)
2,Hispanic / Latino,1 (4.2\%),4 (18.2\%),11 (8.7\%),4 (3.1\%),20 (6.6\%)
3,White / Caucasian,4 (16.7\%),6 (27.3\%),76 (60.3\%),78 (59.5\%),164 (54.1\%)
4,Multiracial / Mixed,0 (0.0\%),0 (0.0\%),10 (7.9\%),4 (3.1\%),14 (4.6\%)
5,Other,0 (0.0\%),0 (0.0\%),2 (1.6\%),0 (0.0\%),2 (0.7\%)
6,Prefer not to say,0 (0.0\%),0 (0.0\%),0 (0.0\%),4 (3.1\%),4 (1.3\%)

### Supplementary Table 4. Matched visual-category FNI by questionnaire associations

,left_label,left_column,right_label,right_column,n,rho,p_value,q_bh,bh,display_source
0,Face FNI,face_fni,AQ,aq_score,153,-0.288895,0.000293,0.002921,yes,active_display_freeze_within_tolerance
1,Face FNI,face_fni,Daily familiarity,daily_familiarity,153,-0.006476,0.936675,0.936675,no,active_display_freeze_within_tolerance
2,Face FNI,face_fni,Flow attitude,flow_original,153,0.201971,0.012293,0.049174,yes,active_display_freeze_within_tolerance
3,Face FNI,face_fni,Maemuki,maemuki_score,153,0.278657,0.000487,0.002921,yes,active_display_freeze_within_tolerance
4,Geometry FNI,geometry_fni,AQ,aq_score,153,0.085959,0.290743,0.697783,no,recomputed
5,Geometry FNI,geometry_fni,Daily familiarity,daily_familiarity,153,0.073375,0.367392,0.699766,no,recomputed
6,Geometry FNI,geometry_fni,Flow attitude,flow_original,153,-0.067341,0.408197,0.699766,no,recomputed
7,Geometry FNI,geometry_fni,Maemuki,maemuki_score,153,-0.150828,0.062743,0.188230,no,recomputed
8,Scenery FNI,scenery_fni,AQ,aq_score,153,0.023184,0.776060,0.846611,no,recomputed
9,Scenery FNI,scenery_fni,Daily familiarity,daily_familiarity,153,0.056845,0.485218,0.726826,no,recomputed
10,Scenery FNI,scenery_fni,Flow attitude,flow_original,153,-0.042062,0.605688,0.726826,no,recomputed
11,Scenery FNI,scenery_fni,Maemuki,maemuki_score,153,-0.043571,0.592799,0.726826,no,recomputed

### Supplementary Table 5. Matched visual-category FNI by Daily familiarity item associations

,left_label,left_column,right_label,right_column,n,rho,p_value,q_bh,bh,display_source
0,Face FNI,face_fni,Books/magazines,daily_books,153,-0.0014,0.98602,0.98602,no,active_display_freeze_within_tolerance
1,Face FNI,face_fni,Clothes,daily_clothes,153,0.0058,0.94285,0.98602,no,active_display_freeze_within_tolerance
2,Face FNI,face_fni,Digital games,daily_games,153,0.0187,0.81863,0.98602,no,active_display_freeze_within_tolerance
3,Face FNI,face_fni,Food/cuisine,daily_food,153,0.0773,0.34256,0.81561,no,active_display_freeze_within_tolerance
4,Face FNI,face_fni,Movies/videos,daily_movies,153,-0.1248,0.12425,0.55304,no,active_display_freeze_within_tolerance
5,Face FNI,face_fni,Places/activities,daily_places,153,-0.0041,0.95997,0.98602,no,active_display_freeze_within_tolerance
6,Face FNI,face_fni,Restaurant,daily_restaurant,153,-0.0413,0.61237,0.95486,no,active_display_freeze_within_tolerance
7,Face FNI,face_fni,Snacks/treats,daily_snacks,153,0.0791,0.33092,0.81561,no,active_display_freeze_within_tolerance
8,Geometry FNI,geometry_fni,Books/magazines,daily_books,153,0.1423,0.07941,0.55304,no,active_display_freeze_within_tolerance
9,Geometry FNI,geometry_fni,Clothes,daily_clothes,153,-0.0366,0.65318,0.95486,no,active_display_freeze_within_tolerance
10,Geometry FNI,geometry_fni,Digital games,daily_games,153,-0.1204,0.13826,0.55304,no,active_display_freeze_within_tolerance
11,Geometry FNI,geometry_fni,Food/cuisine,daily_food,153,0.0282,0.72968,0.97290,no,active_display_freeze_within_tolerance
12,Geometry FNI,geometry_fni,Movies/videos,daily_movies,153,0.0340,0.67636,0.95486,no,active_display_freeze_within_tolerance
13,Geometry FNI,geometry_fni,Places/activities,daily_places,153,0.1515,0.06165,0.55304,no,active_display_freeze_within_tolerance
14,Geometry FNI,geometry_fni,Restaurant,daily_restaurant,153,0.0092,0.90996,0.98602,no,active_display_freeze_within_tolerance
15,Geometry FNI,geometry_fni,Snacks/treats,daily_snacks,153,0.1436,0.07649,0.55304,no,active_display_freeze_within_tolerance
16,Scenery FNI,scenery_fni,Books/magazines,daily_books,153,0.1336,0.09969,0.55304,no,active_display_freeze_within_tolerance
17,Scenery FNI,scenery_fni,Clothes,daily_clothes,153,-0.0182,0.82316,0.98602,no,active_display_freeze_within_tolerance
18,Scenery FNI,scenery_fni,Digital games,daily_games,153,-0.0674,0.40780,0.81561,no,active_display_freeze_within_tolerance
19,Scenery FNI,scenery_fni,Food/cuisine,daily_food,153,0.0359,0.65945,0.95486,no,active_display_freeze_within_tolerance
20,Scenery FNI,scenery_fni,Movies/videos,daily_movies,153,0.0353,0.66477,0.95486,no,active_display_freeze_within_tolerance
21,Scenery FNI,scenery_fni,Places/activities,daily_places,153,0.0723,0.37479,0.81561,no,active_display_freeze_within_tolerance
22,Scenery FNI,scenery_fni,Restaurant,daily_restaurant,153,0.0728,0.37144,0.81561,no,active_display_freeze_within_tolerance
23,Scenery FNI,scenery_fni,Snacks/treats,daily_snacks,153,0.0893,0.27206,0.81561,no,active_display_freeze_within_tolerance

### Supplementary Table 6. Pooled questionnaire-pair associations

,left_label,left_column,right_label,right_column,n,rho,p_value,q_bh,bh
0,Maemuki,maemuki_score,Flow attitude,flow_original,303,0.628447,1.051714e-34,6.310283e-34,yes
1,AQ,aq_score,Maemuki,maemuki_score,303,-0.584342,3.890035e-29,1.167011e-28,yes
2,AQ,aq_score,Flow attitude,flow_original,303,-0.331167,3.456314e-09,6.912628e-09,yes
3,AQ,aq_score,Daily familiarity,daily_familiarity,303,0.234495,3.746431e-05,5.619647e-05,yes
4,Daily familiarity,daily_familiarity,Maemuki,maemuki_score,303,-0.214260,1.713335e-04,2.056002e-04,yes
5,Daily familiarity,daily_familiarity,Flow attitude,flow_original,303,-0.074482,1.960339e-01,1.960339e-01,no

### Supplementary Table 7. Pooled Daily familiarity item by questionnaire associations

,left_label,left_column,right_label,right_column,n,rho,p_value,q_bh,bh
0,Books/magazines,daily_books,AQ,aq_score,303,0.132164,0.021383,0.064149,no
1,Books/magazines,daily_books,Flow attitude,flow_original,303,-0.034224,0.552887,0.663464,no
2,Books/magazines,daily_books,Maemuki,maemuki_score,303,-0.085079,0.139534,0.223255,no
3,Clothes,daily_clothes,AQ,aq_score,303,0.101422,0.077952,0.133632,no
4,Clothes,daily_clothes,Flow attitude,flow_original,303,0.012669,0.826161,0.901267,no
5,Clothes,daily_clothes,Maemuki,maemuki_score,303,-0.115038,0.045412,0.102476,no
6,Digital games,daily_games,AQ,aq_score,303,0.070184,0.223173,0.315067,no
7,Digital games,daily_games,Flow attitude,flow_original,303,-0.000648,0.991043,0.997063,no
8,Digital games,daily_games,Maemuki,maemuki_score,303,-0.027413,0.634584,0.725239,no
9,Food/cuisine,daily_food,AQ,aq_score,303,0.256691,0.000006,0.000144,yes
10,Food/cuisine,daily_food,Flow attitude,flow_original,303,-0.055530,0.335367,0.447156,no
11,Food/cuisine,daily_food,Maemuki,maemuki_score,303,-0.166928,0.003566,0.017119,yes
12,Movies/videos,daily_movies,AQ,aq_score,303,0.112788,0.049829,0.102476,no
13,Movies/videos,daily_movies,Flow attitude,flow_original,303,-0.071684,0.213414,0.315067,no
14,Movies/videos,daily_movies,Maemuki,maemuki_score,303,-0.154478,0.007059,0.028236,yes
15,Places/activities,daily_places,AQ,aq_score,303,0.209172,0.000246,0.001966,yes
16,Places/activities,daily_places,Flow attitude,flow_original,303,-0.110127,0.055508,0.102476,no
17,Places/activities,daily_places,Maemuki,maemuki_score,303,-0.214175,0.000172,0.001966,yes
18,Restaurant,daily_restaurant,AQ,aq_score,303,0.187907,0.001014,0.006082,yes
19,Restaurant,daily_restaurant,Flow attitude,flow_original,303,-0.000212,0.997063,0.997063,no
20,Restaurant,daily_restaurant,Maemuki,maemuki_score,303,-0.140591,0.014313,0.049072,yes
21,Snacks/treats,daily_snacks,AQ,aq_score,303,0.118495,0.039268,0.102476,no
22,Snacks/treats,daily_snacks,Flow attitude,flow_original,303,-0.040396,0.483584,0.610842,no
23,Snacks/treats,daily_snacks,Maemuki,maemuki_score,303,-0.112039,0.051377,0.102476,no

### Supplementary Table 8. Questionnaire relationships in the joint model

,path_id,analysis_sample,relationship,n,standardized_coefficient,ci_low,ci_high,ci_excludes_zero,n_bootstrap,seed,recomputed_check
0,Daily_to_Flow,Primary QC-clean,Daily familiarity $\rightarrow$ Flow (common 12),303,0.022,-0.080,0.121,no,10000,20260724,0.022091
1,AQ_to_Flow,Primary QC-clean,AQ $\rightarrow$ Flow (common 12),303,-0.348,-0.448,-0.240,yes,10000,20260724,-0.347399
2,AQ_to_Maemuki,Primary QC-clean,AQ $\rightarrow$ Maemuki,303,-0.398,-0.476,-0.322,yes,10000,20260724,-0.398039
3,Flow_to_Maemuki,Primary QC-clean,Flow (common 12) $\rightarrow$ Maemuki,303,0.514,0.432,0.591,yes,10000,20260724,0.513894
4,Daily_with_AQ,Primary QC-clean,Daily familiarity--AQ correlation,303,0.229,0.125,0.329,yes,10000,20260724,0.229140

### Supplementary Table 9. Primary category trajectories and pairwise differences

,panel,estimand,estimate,se,ci_low,ci_high,p_value,q_bh
0,a,Face,0.01337,.00285,0.00778,0.01896,2.730000e-06,--
1,a,Scenery,-0.01763,.00285,-0.02322,-0.01204,6.260000e-10,--
2,a,Geometry,0.00131,.00285,-0.00428,0.00690,6.460000e-01,--
3,b,Face -- Scenery,0.03100,--,0.02310,0.03890,1.490000e-14,4.46e-14
4,b,Face -- Geometry,0.01206,--,0.00416,0.01996,2.780000e-03,.00278
5,b,Scenery -- Geometry,-0.01894,--,-0.02684,-0.01104,2.640000e-06,3.95e-6

### Supplementary Table 10. Sensitivity analyses for the category trajectories

,panel,estimand,estimate,se,ci_low,ci_high,p_value,q_bh
0,a,Face slope,0.01337,0.00278,0.00792,0.01882,1.540000e-06,--
1,a,Scenery slope,-0.01763,0.00403,-0.02552,-0.00974,1.190000e-05,--
2,a,Geometry slope,0.00131,0.00391,-0.00636,0.00898,7.378500e-01,--
3,a,Face -- Scenery,0.03100,0.00476,0.02166,0.04034,7.750000e-11,2.32e-10
4,a,Face -- Geometry,0.01206,0.00451,0.00322,0.02090,7.480000e-03,.00748
5,a,Scenery -- Geometry,-0.01894,0.00558,-0.02988,-0.00799,6.950000e-04,.00104
6,b,Face slope,0.01336,0.00726,-0.00087,0.02760,6.580000e-02,--
7,b,Scenery slope,-0.01819,0.00305,-0.02417,-0.01222,2.440000e-09,--
8,b,Geometry slope,0.00112,0.00368,-0.00610,0.00834,7.610000e-01,--
9,b,Face -- Scenery,0.03156,0.00814,0.01560,0.04751,1.060000e-04,0.000159
10,b,Face -- Geometry,0.01224,0.00870,-0.00480,0.02929,1.590000e-01,0.159
11,b,Scenery -- Geometry,-0.01931,0.00474,-0.02861,-0.01001,4.690000e-05,0.000141

### Supplementary Table 11. Overall-moderator trajectory family and item-aware sensitivity

,category,moderator,b,se_hlm,p_hlm,q_hlm,se_cr1,p_cr1,q_cr1,cr1_bh
0,Face,AQ,-0.00046,0.00041,0.25676,0.73238,0.00030,0.12433,0.49731,no
1,Face,Daily familiarity,0.00101,0.00285,0.72204,0.81317,0.00271,0.70818,0.86037,no
2,Face,Maemuki,0.00489,0.00476,0.30516,0.73238,0.00463,0.29125,0.75095,no
3,Face,Flow Attitude,0.00337,0.00447,0.45059,0.77245,0.00381,0.37548,0.75095,no
4,Scenery,AQ,0.00010,0.00041,0.80803,0.81317,0.00056,0.86037,0.86037,no
5,Scenery,Daily familiarity,0.00670,0.00285,0.01879,0.11273,0.00429,0.11807,0.49731,no
6,Scenery,Maemuki,-0.00220,0.00476,0.64425,0.81317,0.00701,0.75350,0.86037,no
7,Scenery,Flow Attitude,0.00589,0.00447,0.18761,0.73238,0.00636,0.35427,0.75095,no
8,Geometry,AQ,-0.00010,0.00041,0.81317,0.81317,0.00054,0.85723,0.86037,no
9,Geometry,Daily familiarity,-0.00245,0.00285,0.39043,0.77245,0.00430,0.56873,0.86037,no
10,Geometry,Maemuki,-0.00167,0.00476,0.72627,0.81317,0.00481,0.72871,0.86037,no
11,Geometry,Flow Attitude,-0.01426,0.00447,0.00143,0.01712,0.00467,0.00224,0.02684,yes

### Supplementary Table 12. Joint-trait trajectory-moderation sensitivity

,category,trait,b,se,z,p,q_bh,bh
0,Face,AQ,-0.00032,0.00053,-0.614,0.53944,0.91819,no
1,Face,Maemuki,0.00099,0.00765,0.129,0.89709,0.91819,no
2,Face,Flow Attitude,0.00061,0.00590,0.103,0.91819,0.91819,no
3,Face,Negative Capability,0.00138,0.00464,0.297,0.76643,0.91819,no
4,Scenery,AQ,-0.00007,0.00053,-0.140,0.88883,0.91819,no
5,Scenery,Maemuki,-0.01103,0.00765,-1.442,0.14927,0.35824,no
6,Scenery,Flow Attitude,0.01103,0.00590,1.870,0.06143,0.18429,no
7,Scenery,Negative Capability,0.00131,0.00464,0.283,0.77750,0.91819,no
8,Geometry,AQ,-0.00029,0.00053,-0.549,0.58313,0.91819,no
9,Geometry,Maemuki,0.01540,0.00765,2.014,0.04404,0.18429,no
10,Geometry,Flow Attitude,-0.01802,0.00590,-3.054,0.00226,0.02708,yes
11,Geometry,Negative Capability,-0.00886,0.00464,-1.910,0.05609,0.18429,no

### Supplementary Table 13. Daily-item moderation family and item-aware sensitivity

,category,daily_item,b,se_hlm,p_hlm,q_hlm,se_cr1,p_cr1,q_cr1,cr1_bh
0,Face,Food/cuisine,0.00039,0.00285,0.890900,0.96814,0.00262,0.88141,0.97729,no
1,Face,Places/activities,0.00026,0.00285,0.926110,0.96814,0.00244,0.91382,0.97729,no
2,Face,Movies/videos,-0.00321,0.00285,0.260060,0.62415,0.00258,0.21370,0.59905,no
3,Face,Restaurant,0.00110,0.00285,0.698390,0.89310,0.00251,0.65952,0.97729,no
4,Face,Clothes,0.00352,0.00285,0.216330,0.57689,0.00236,0.13535,0.59905,no
5,Face,Digital games,0.00018,0.00285,0.949590,0.96814,0.00321,0.95520,0.97729,no
6,Face,Books/magazines,0.00058,0.00285,0.837870,0.96814,0.00296,0.84395,0.97729,no
7,Face,Snacks/treats,0.00259,0.00285,0.362850,0.72570,0.00262,0.32197,0.70248,no
8,Scenery,Food/cuisine,0.00151,0.00285,0.595480,0.89310,0.00453,0.73807,0.97729,no
9,Scenery,Places/activities,0.00513,0.00285,0.071770,0.33773,0.00372,0.16796,0.59905,no
10,Scenery,Movies/videos,-0.00116,0.00285,0.683990,0.89310,0.00408,0.77594,0.97729,no
11,Scenery,Restaurant,0.00969,0.00285,0.000677,0.00812,0.00378,0.01049,0.12586,no
12,Scenery,Clothes,0.00011,0.00285,0.968140,0.96814,0.00400,0.97729,0.97729,no
13,Scenery,Digital games,0.00492,0.00285,0.084430,0.33773,0.00424,0.24601,0.59905,no
14,Scenery,Books/magazines,0.00243,0.00285,0.393560,0.72656,0.00440,0.58045,0.97729,no
15,Scenery,Snacks/treats,0.01156,0.00285,0.000050,0.00119,0.00378,0.00220,0.05279,no
16,Geometry,Food/cuisine,0.00418,0.00285,0.142480,0.42745,0.00359,0.24359,0.59905,no
17,Geometry,Places/activities,0.00107,0.00285,0.707030,0.89310,0.00388,0.78272,0.97729,no
18,Geometry,Movies/videos,-0.00431,0.00285,0.130810,0.42745,0.00374,0.24961,0.59905,no
19,Geometry,Restaurant,-0.00571,0.00285,0.045010,0.27004,0.00364,0.11687,0.59905,no
20,Geometry,Clothes,-0.00628,0.00285,0.027530,0.22023,0.00367,0.08697,0.59905,no
21,Geometry,Digital games,-0.00287,0.00285,0.313400,0.68378,0.00323,0.37369,0.74738,no
22,Geometry,Books/magazines,0.00116,0.00285,0.685060,0.89310,0.00306,0.70601,0.97729,no
23,Geometry,Snacks/treats,0.00212,0.00285,0.457370,0.78406,0.00362,0.55795,0.97729,no

### Supplementary Table 14. Cross-subcategory stability

,measure,face,face_low,face_high,scenery,scenery_low,scenery_high,geometry,geometry_low,geometry_high
0,Category-specific FNI,0.235,0.061,0.396,0.469,0.348,0.579,0.323,0.157,0.473
1,Category-specific trajectory slope,-0.322,-0.601,-0.060,0.068,-0.157,0.270,0.071,-0.150,0.268

### Supplementary Table 15. Task-pool stimulus taxonomy across Experiments 1–5

    category                     subcategory  E1  E2  E3  E4  E5
0       Face            Female--Asian--Adult   1   1   1   1   1
1       Face      Female--Asian--Young-adult   1   1   1   1   1
2       Face            Female--Black--Adult   1   1   1   1   1
3       Face      Female--Black--Young-adult   1   1   1   1   1
4       Face           Female--Latino--Adult   1   1   1   1   1
5       Face     Female--Latino--Young-adult   1   1   1   1   1
6       Face            Female--White--Adult   1   1   1   1   1
7       Face      Female--White--Young-adult   1   1   1   1   1
8       Face              Male--Asian--Adult   1   1   1   1   1
9       Face        Male--Asian--Young-adult   1   1   1   1   1
10      Face              Male--Black--Adult   1   1   1   1   1
11      Face        Male--Black--Young-adult   1   1   1   1   1
12      Face             Male--Latino--Adult   1   1   1   1   1
13      Face       Male--Latino--Young-adult   1   1   1   1   1
14      Face              Male--White--Adult   1   1   1   1   1
15      Face        Male--White--Young-adult   1   1   1   1   1
16   Scenery                           Beach   1   0   1   1   1
17   Scenery                          Desert   1   0   1   1   1
18   Scenery                          Flower   1   0   0   0   0
19   Scenery                            Lake   1   0   0   0   0
20   Scenery                        Mountain   1   1   1   1   1
21   Scenery                           River   1   1   1   1   1
22   Scenery                             Sky   1   0   0   0   0
23  Geometry  Complex (symmetry not encoded)   1   1   0   0   0
24  Geometry   Simple (symmetry not encoded)   1   1   0   0   0
25  Geometry             Complex--asymmetric   0   0   1   1   1
26  Geometry              Complex--symmetric   0   0   1   1   1
27  Geometry              Simple--asymmetric   0   0   1   1   1
28  Geometry               Simple--symmetric   0   0   1   1   1
29       Car                  Diagonal sedan   1   0   0   0   0
30       Car             Diagonal sports car   1   1   0   0   0
31       Car                    Diagonal SUV   1   1   0   0   0
32       Car                  Diagonal truck   1   0   0   0   0
33       Car                     Front sedan   1   0   0   0   0
34       Car                Front sports car   1   0   0   0   0
35       Car                       Front SUV   1   0   0   0   0
36       Car                     Front truck   1   0   0   0   0

### Supplementary Table 16. Questionnaire-derived features used in Experiments 2–5

,feature,construct,items_source,scoring,interpretation
0,1_Trust-Integrity,Trust and integrity orientation,11 trust-related items,Mean of 11 Likert items; standard items scored...,"Higher = stronger trust in others, honesty, ki..."
1,2_Emotion-Coping,Emotion regulation and coping,12 emotion/coping items,Mean of 12 Likert items after reverse coding,Higher = stronger adaptive emotion regulation ...
2,3_Social-self,Social self-expression and interpersonal self-...,15 social/self-expression items,Mean of 15 Likert items after reverse coding,"Higher = stronger social openness, self-expres..."
3,4_food/cuisine,Daily novelty/familiarity in food choices,1 daily-life behavior item,"$-$3 = Always New, 0 = Intermediate, $+$3 = Fa...",Higher = more familiar food choices; lower = m...
4,4_places/activities,Daily novelty/familiarity in places and activi...,1 daily-life behavior item,$-$3 to $+$3 novelty/familiarity coding,Higher = more familiar places/activities; lowe...
5,4_movies or videos,Daily novelty/familiarity in media choices,1 daily-life behavior item,$-$3 to $+$3 novelty/familiarity coding,Higher = more familiar movies/videos; lower = ...
6,4_restaurant,Daily novelty/familiarity in restaurant choices,1 daily-life behavior item,$-$3 to $+$3 novelty/familiarity coding,Higher = more familiar restaurant choices; low...
7,4_clothes,Daily novelty/familiarity in clothing choices,1 daily-life behavior item,$-$3 to $+$3 novelty/familiarity coding,Higher = more familiar clothing choices; lower...
8,4_digital games,Daily novelty/familiarity in digital games,1 daily-life behavior item,$-$3 to $+$3 novelty/familiarity coding,Higher = more familiar game choices; lower = m...
9,4_books or magazines,Daily novelty/familiarity in reading choices,1 daily-life behavior item,$-$3 to $+$3 novelty/familiarity coding,Higher = more familiar reading choices; lower ...
10,4_snacks or treats,Daily novelty/familiarity in snack choices,1 daily-life behavior item,$-$3 to $+$3 novelty/familiarity coding,Higher = more familiar snack choices; lower = ...
11,4_NF-daily,Overall daily novelty/familiarity tendency,Mean of 8 daily-life domains,Mean of the 8 \texttt{4\_} daily behavior items,Higher = stronger familiarity-seeking in daily...
12,4_1_N-affect_daily,Self-reported lifestyle impact of novelty-seeking,2 past-six-month items: novelty-seeking made l...,Mean of the 2 novelty-seeking impact items sco...,Higher = stronger self-reported positive lifes...
13,4_2_F-affect_daily,Self-reported lifestyle impact of familiarity-...,2 past-six-month items: familiarity-seeking ma...,Mean of the 2 familiarity-seeking impact items...,Higher = stronger self-reported positive lifes...
14,5_Social-oppo-group,Social opportunity and group mobility,"12 items about meeting people, social options,...",Mean of 12 Likert items after reverse coding,Higher = greater perceived social opportunity ...
15,6_Other-social,Perceived social environment of others,12 items about people the respondent regularly...,Mean of 12 Likert items after reverse coding,Higher = respondent perceives surrounding othe...
16,7_Personal_resp-self_disp,Personal responsibility and self-discipline,19 responsibility/self-discipline items,Mean of 19 Likert items after reverse coding,"Higher = stronger responsibility, persistence,..."
17,8_Communi_Family,Community and family engagement,14 community/family items,Mean of 14 Likert items scored $-$3 to $+$3,Higher = stronger family/community connection ...
18,9_Growth_Reflect,Personal growth and self-reflection,16 personal growth/reflection items,Mean of 16 Likert items after reverse coding,Higher = stronger growth orientation and refle...
19,10_Flow-attitude,General flow orientation,12 flow-related items,Mean of 12 Likert items after reverse coding,"Higher = stronger positive attitude, desire, a..."
20,10_Flow_belief_tendency,Belief/value placed on flow,First 4 flow items,Mean of 4 scored flow items,Higher = stronger belief that flow is valuable...
21,10_Flow_desire_tendency,Desire for flow,One flow-related desire item,Single Likert item scored $-$3 to $+$3,Higher = stronger desire to experience flow
22,10_Flow_real_tendency,Actual flow experience tendency,2 flow-experience items,Mean of 2 scored flow items,Higher = more reported real-life flow experience
23,11_Self_percept-worth,Self-perception and self-worth,10 self-worth items,Mean of 10 Likert items after reverse coding,Higher = stronger positive self-perception and...
24,12_Negative_Capability,Negative capability / adaptive tolerance of un...,9 negative-capability items; Experiments 3--5 ...,Mean of 9 Likert items scored $-$3 to $+$3,Higher = stronger ability to tolerate uncertai...
25,AQ_score,Autism-spectrum trait score,50 Autism-Spectrum Quotient items,"Binary scoring per item, then summed; each ite...",Higher = stronger autistic-trait tendency
26,Maemuki_score,Broad positive/forward psychological orientation,"Composite of 9 subscales: 1, 2, 3, 5, 6, 7, 8,...",Mean of the 9 questionnaire subscale scores,"Higher = more positive, socially engaged, self..."

### Supplementary inline result 1. Main-text to Supplementary Information cross-reference

,main_text_result,supplement_location,interpretation_boundary
0,Study design (\textcolor{blue}{Fig.~1}) and Me...,"Cohorts and demographics (Section~2), addition...","Core outcome, FNI and trajectory definitions a..."
1,Visual trajectories (\textcolor{blue}{Fig.~5a}),"Model estimates, planned contrasts and sensiti...",Primary inference uses the matched Experiment~...
2,Individual profiles (\textcolor{blue}{Fig.~2b}),Category-pattern counts and selected-case comp...,Descriptive only; no discrete participant-type...
3,Matched FNI associations (\textcolor{blue}{Fig...,"Reliability, complete association families and...",The FNI is defined in the main Methods; these ...
4,Integrated questionnaire associations (\textco...,"Complete pooled correlations, the joint questi...",\textbf{Secondary} or exploratory and cross-se...
5,Trajectory moderators (\textcolor{blue}{Fig.~5...,"Complete moderator families, item-aware infere...",\textit{Exploratory}; Daily-item candidates ar...
6,Questionnaire battery (\textcolor{blue}{Fig.~1...,Reconstruction and reliability (Section~8.2; S...,Measurement implementations differed across ex...

### Supplementary inline result 2. Face-FNI adjusted and joint-model robustness

   measure  adjusted_r    q_bh  joint_beta  p_value
0       AQ      -0.250  0.0132      -0.143    0.158
1  Maemuki       0.263  0.0132       0.115    0.384
2     Flow       0.208  0.0388       0.087    0.412

Displayed all 16 numbered Supplementary Tables and both supplementary inline results.

## 5. Verify analysis consistency, figure content, tables, and privacy minimization

Acceptance requires the exact artboards, expected extracted text, the declared raster policy, all table fragments, agreement between recomputed and frozen correlation families, and the namespace/minimization scan. Analysis figures remain vector-only; Main Figure 1 permits its embedded stimulus images. Binary PDF hashes remain provenance only because harmless metadata and object-order differences change file bytes.

In [6]:
figure_validation = pd.read_csv(ROOT / 'outputs' / 'figure_validation.csv')
table_validation = pd.read_csv(ROOT / 'outputs' / 'table_validation.csv')
privacy_validation = pd.read_csv(ROOT / 'outputs' / 'data_privacy_validation.csv')
analysis_crosscheck = pd.read_csv(ROOT / 'outputs' / 'analysis_crosscheck.csv')

assert figure_validation['artboard_ok'].all()
assert figure_validation['content_ok'].all()
assert figure_validation['raster_policy_ok'].all()
assert table_validation['exists'].all()
assert privacy_validation['public_identifier_check'].all()
assert privacy_validation['namespace_and_minimization_check'].all()
assert analysis_crosscheck['within_tolerance'].all()

display(figure_validation[['figure', 'observed_width_pt', 'observed_height_pt', 'artboard_ok', 'required_text_found', 'vector_only', 'raster_policy_ok', 'content_ok']])
display(analysis_crosscheck)
print(f"Validated {len(table_validation)} table fragments and {len(privacy_validation)} public CSV files.")

,figure,observed_width_pt,observed_height_pt,artboard_ok,required_text_found,vector_only,raster_policy_ok,content_ok
0,Main Figure 1,518.000,346.000000,True,True,False,True,True
1,Main Figure 2,345.600,324.480000,True,True,True,True,True
2,Main Figure 3,345.600,320.400000,True,True,True,True,True
3,Main Figure 4,345.600,450.000000,True,True,True,True,True
4,Main Figure 5,345.600,357.165354,True,True,True,True,True
5,Supplementary Figure 1,510.236,459.213000,True,True,True,True,True
6,Supplementary Figure 2,509.760,297.600000,True,True,True,True,True
7,Supplementary Figure 3,510.236,297.638000,True,True,True,True,True
8,Supplementary Figure 4,510.236,566.929000,True,True,True,True,True
9,Supplementary Figure 5,518.400,146.880000,True,True,True,True,True
10,Supplementary Figure 6,237.600,189.360000,True,True,True,True,True
11,Supplementary Figure 7,509.760,260.640000,True,True,True,True,True
12,Supplementary Figure 8,510.236,328.819000,True,True,True,True,True
13,Supplementary Figure 9,510.236,232.441000,True,True,True,True,True
14,Supplementary Figure 10,345.600,547.200000,True,True,True,True,True
15,Supplementary Figure 11,509.760,334.080000,True,True,True,True,True

,analysis_family,matched_rows,expected_rows,missing_keys,all_n_match,max_rho_absolute_error,max_q_absolute_error,tolerance,within_tolerance
0,Main Figure 3 BH-12 / Supplementary Table 4,12,12,NaN,True,4.132387e-07,3.383250e-07,0.0005,True
1,Main Figure 3 BH-24 / Supplementary Table 5,24,24,NaN,True,4.947821e-05,4.753539e-06,0.0005,True
2,Main Figure 4 BH-6 / Supplementary Table 6,6,6,NaN,True,0.000000e+00,0.000000e+00,0.0005,True
3,Main Figure 4 BH-24 / Supplementary Table 7,24,24,NaN,True,0.000000e+00,0.000000e+00,0.0005,True

Validated 18 table fragments and 56 public CSV files.

## Interpretation and release notes

The N-F-1 IDs `E1A001`–`E1A015` are release-only pseudonyms and are not linked to archived filenames or later experiments. The manuscript profile IDs `P092` and `P101` are author-selected descriptive examples, not clusters or participant types. They map to release analysis records `A242` and `A251`; the two namespaces must not be joined by their numeric suffix. Figure 5 keeps the matched E3/E5 trajectory cohort separate from the pooled questionnaire cohort, and all multiplicity families and sensitivity labels are retained.

The automated privacy checks support data minimization but do not establish legal or ethical de-identification. Obtain corresponding-author/data-controller approval under the applicable consent, ethics/IRB, and institutional data-sharing terms before publishing participant-level derived rows or age points.